if not pocket then
    print("Please use a pocket computer.")
    return
end
print("Making Ipodsys Dir")
fs.makeDir("ipodsys")
print("Making Ipodusr Dir")
fs.makeDir("ipodusr")
print("Installing Updater")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/updater.lua updater.lua")
print("CDing into ipodsys to install")
shell.run("cd ipodsys")
print("Installing Ipodmenu")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/ipodmenu.lua ipodmenu.lua")
print("Installing App Menu")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/appmenu.lua appmenu.lua")
print("Installing Music")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/music.lua music.lua")
print("Installing Settings")
shell.run("wget  https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/settings.lua settings.lua")
print("Installing Snake")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/snake.lua snake.lua")
print("Installing Calculator")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/calc.lua calc.lua")
print("Installing Browser")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/ccbrowser.lua ccbrowser.lua")
print("Installing Paint")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/Paint.lua Paint.lua")
print("CDing to rom to create settings.txt")
shell.run("cd ..")
print("creating and writing to settings")
local id = math.random(1,255)
if not fs.exists("settings.txt") then
  local file = fs.open("settings.txt","w")
  file.write("User" .. "\n" .. id .. "\n" .. "Dark")
  file.close()
end
print("Finishing installation")
sleep(0.5)
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/startup.lua startup.lua")
os.reboot()
