if not pocket then
    print("Please use a pocket computer.")
    return
elseif not advanced then
    print("Please use a ADVANCED pocket computer.")
    return
end
print("Making System Dir")
fs.makeDir("ipodsys")
print("Making User Dir")
fs.makeDir("ipodusr")
print("Making Apps Dir")
fs.makeDir("ipodapps")
print("Making Api Dir")
fs.makeDir("apis")
print("Installing Updater")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/updater.lua updater.lua")
print("CDing into ipodsys to install")
shell.run("cd ipodsys")
print("Installing Ipodmenu")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/ipodmenu.lua ipodmenu.lua")
print("Installing App Menu")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/appmenu.lua appmenu.lua")
print("Installing Music")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/music.lua music.lua")
print("Installing Settings")
shell.run("wget  https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/settings.lua settings.lua")
print("Installing Snake")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/snake.lua snake.lua")
print("Installing Calculator")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/calc.lua calc.lua")
print("Installing Browser")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/ccbrowser.lua ccbrowser.lua")
print("Installing Paint")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/Paint.lua Paint.lua")
print("Installing Custom App Browser")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/cab.lua cab.lua")
print("Installing App Store")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/ipodsys/appstore.lua appstore.lua")
print("CDing to rom to create settings.txt")
shell.run("cd ..")
print("creating and writing to settings")
local id = math.random(1,255)
if not fs.exists("settings.txt") then
  local file = fs.open("settings.txt","w")
  file.write("User" .. "\n" .. id .. "\n" .. "Dark")
  file.close()
end
print("Finishing installation")
sleep(0.5)
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/startup.lua startup.lua")
shell.run("cd apis")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/apis/speedycoding speedycoding")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/nightly/apis/uilib uilib")
os.reboot()
