print("Deleting ipodsys")
shell.run("cd ..")
fs.delete("ipodsys")
print("Remaking ipodsys")
fs.makeDir("ipodsys")
print("CDing into ipodsys to install")
shell.run("cd ipodsys")
print("Installing Ipodmenu")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/ipodmenu.lua ipodmenu.lua")
print("Installing App Menu")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/appmenu.lua appmenu.lua")
print("Installing Music")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/music.lua music.lua")
print("Installing Settings")
shell.run("wget  https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/settings.lua settings.lua")
print("Installing Snake")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/snake.lua snake.lua")
print("Installing Calculator")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/calc.lua calc.lua")
print("Installing Browser")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/ccbrowser.lua ccbrowser.lua")
print("Installing Notepad")
shell.run("wget https://raw.githubusercontent.com/kaykaypoopaa/Ipod-CC-Tweaked/refs/heads/main/ipodsys/notepad.lua notepad.lua")