term.clear()
term.setCursorPos(1, 1)
print("What file do you want to edit?")
sleep(0.5)
local file = read()
sleep(0.05)
term.clear()
print("Opening")
shell.run("cd ..")
shell.run("edit ipodusr/" .. file .. ".txt")