term.clear()
term.setCursorPos(1, 1)
print("What picture do you want to edit?")
sleep(0.5)
local picture = read()
sleep(0.05)
term.clear()
print("Opening")
shell.run("cd ..")
shell.run("paint ipodusr/" .. picture .. ".nfp")
